#!/usr/bin/env python3.11

# Copyright (C) 2024-2026 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

try:
    from teatype.cli import BaseStartCLI
except:
    print()
    print('Error: The "teatype" package is required to run this script.')
    print()
    print('If there is supposed to be a venv in the root directory of this project, check if it is missing.')
    print('Otherwise activate it either manually:')
    print('     $ . <venv_name>/bin/activate')
    print()
    print('Or, if you have the Cir.Log aliases injected, you can also run this command after navigating')
    print('to the root-directory of this project and activate the venv automatically:')
    print('     $ pv')
    print()
    print('Alternatively, you can activate the cli-venv (again, if aliases have been injected) and try to run the script again:')
    print('     $ clv')
    print()
    print('You can also use the Cir.Log-CLI (if installed) instead:')
    print('     $ cl start <module>')
    print()
    exit(1)

class Start(BaseStartCLI):
    REQUIRES_SSL=False
        
    def pre_execute(self):
        self.process_name = 'server'

if __name__ == '__main__':
    Start()