#!/usr/bin/env python3.11

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Third-party imports
from teatype.cli import BaseTUI

# TODO: HTTP status codes
class Codes(BaseTUI):
    def meta(self):
        return {
            'name': 'codes',
            'shorthand': 'cs',
            'help': 'Display various status codes',
            'commands': [
                {
                    'name': 'http',
                    'shorthand': 'ht',
                    'help': 'Display all HTTP status codes',
                },
                {
                    'name': 'state',
                    'shorthand': 'st',
                    'help': 'Display all custom state codes',
                },
                {
                    'name': 'unicode',
                    'shorthand': 'un',
                    'help': 'Display useful unicode characters',
                }
            ]
        }
        
    def get_http_codes(self):
        # TODO: Read from a file
        pass
    
    def get_state_codes(self):
        # TODO: Read from package
        pass
    
    def get_unicodes(self):
        # TODO: Read from a file
        useful_unicode_characters = [
            'ඞ'
        ]
        pass
    
    def make_clickable_link(self, text_to_copy):
        # Encode the text as a "fake URL" to copy it.
        encoded_text = text_to_copy.replace(" ", "%20")
        print(f"\033]8;;copy://{encoded_text}\033\\Click here to copy: {text_to_copy}\033]8;;\033\\")

    def execute(self):
        selected_code_type = self.get_command()
        match selected_code_type:
            case 'http':
                codes = self.get_http_codes()
            case 'state':
                codes = self.get_state_codes()
            case 'unicode':
                codes = self.get_unicodes()
        print(codes)
                
if __name__ == '__main__':
    Codes()