#!/usr/bin/env python3.11

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Third-party imports
from teatype.cli import BaseCLI

class ImportSchema(BaseCLI):
    def meta(self):
        return {
            'name': 'import-schema',
            'shorthand': 'is',
            'help': 'List the import schemas',
            'commands': [
                {
                    'name': 'all',
                    'shorthand': 'a',
                    'help': 'List all import schema',
                },
                {
                    'name': 'go',
                    'shorthand': 'g',
                    'help': 'List the go import schema',
                },
                {
                    'name': 'python',
                    'shorthand': 'py',
                    'help': 'List the python import schema',
                },
                {
                    'name': 'typescript',
                    'shorthand': 'ts',
                    'help': 'List the typescript import schema',
                }
            ]
        }

    def execute(self):
        pass

if __name__ == '__main__':
    ImportSchema()