#!/bin/bash

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

workspace_directory=$(dirname "$(readlink -f "$0")") # teatype/scripts/deploy
parent_directory=$(dirname "$workspace_directory") # teatype/scripts
grandparent_directory=$(dirname "$parent_directory") # teatype
. "$grandparent_directory/util/bash-helper.sh"

prepare_sudo_env

$workspace_directory/1-install-python311
$workspace_directory/2-create-env
$workspace_directory/3-install-dev-environment
$workspace_directory/5-install-system-dependencies

env_path="$grandparent_directory/.env"
. "$env_path"

if [[ ":$PATH:" != *":/usr/local/bin:"* ]]; then
    echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bashrc
    echo "Added /usr/local/bin to PATH in ~/.bashrc"
fi

cli_path="$grandparent_directory/cli"
input_file="$cli_path/proxy.template"
output_file="/usr/local/bin/tt"

sudo rm -f "$output_file"

sed -e "s|{{WORKSPACE_PATH}}|$grandparent_directory|g" "$input_file" | sudo tee "$output_file" >/dev/null

sudo chmod a+x "$cli_path/tt"
sudo chmod a+x "$input_file"
sudo chmod a+x "$output_file"
echo "Processed script saved to $output_file"

exec bash