#!/bin/bash

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

grandparent_directory=$(dirname "$(readlink -f "$0")")
parent_directory=$(dirname "$grandparent_directory")
grandparent_directory=$(dirname "$parent_directory")
. "$grandparent_directory/util/bash-helper.sh"

prepare_sudo_env

# ./2-create-env
# ./3-install-python311

# sudo apt-get install -y libgl1-mesa-glx || true
# sudo apt-get install -y libgl1 libglx-mesa0 || true
# sudo apt-get install -y chromium-browser vim graphviz openjdk-17-jre-headless jq

# . "$env_path"

# if [[ ":$PATH:" != *":/usr/local/bin:"* ]]; then
#     echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bashrc
#     echo "Added /usr/local/bin to PATH in ~/.bashrc"
# fi

# input_file="$cli_path/proxy.template"
# output_file="/usr/local/bin/tt"
# sudo rm -f "$output_file"

# sed -e "s|{{WORKSPACE_PATH}}|$grandparent_directory|g" "$input_file" | sudo tee "$output_file" >/dev/null

# sudo chmod a+x "$cli_path/tt"
# sudo chmod a+x "$input_file"
# sudo chmod a+x "$output_file"
# echo "Processed script saved to $output_file"

# exec bash