#!/bin/bash

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

grandparent_directory=$(dirname "$(readlink -f "$0")")
parent_directory=$(dirname "$grandparent_directory")
grandparent_directory=$(dirname "$parent_directory")
. "$grandparent_directory/util/bash-helper.sh"

prepare_sudo_env

sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt-get update -y
sudo apt install -y python3.11 python3.11-dev python3.11-venv python3-pip