#!/bin/bash

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

grandparent_directory=$(dirname "$(readlink -f "$0")")
parent_directory=$(dirname "$grandparent_directory")
grandparent_directory=$(dirname "$parent_directory")
. "$grandparent_directory/util/bash-helper.sh"

env_path="$grandparent_directory/.env"
cp "$grandparent_directory/.env.template" "$env_path"
if $(uname -r | grep -q "WSL"); then
    echo "Detected WSL instance. Setting flag in .env"
    write_env_variable "$grandparent_directory/.env" "USING_WSL" "true"
    if [ -n "$WSL_DISTRO_NAME" ]; then
        echo "Detected WSL profile: "$WSL_DISTRO_NAME". Writing to .env"
        write_env_variable "$grandparent_directory/.env" "WSL_TARGET_PROFILE" "$WSL_DISTRO_NAME"
    fi
else
    echo "Not running inside WSL. Setting flag in .env"
    write_env_variable "$grandparent_directory/.env" "USING_WSL" "false"
fi

cli_path="$grandparent_directory/cli"
python_path="$grandparent_directory/python"
typescript_path="$grandparent_directory/typescript"

write_env_variable "$env_path" "TEATYPE_CLI_PATH" "$cli_path" 
write_env_variable "$env_path" "TEATYPE_PYTHON_PATH" "$python_path" 
write_env_variable "$env_path" "TEATYPE_TYPESCRIPT_PATH" "$typescript_path" 
write_env_variable "$env_path" "TEATYPE_WORKSPACE_PATH" "$grandparent_directory"