#!/bin/bash

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

cleanup() {
    deactivate > /dev/null 2>&1 || true
    sudo rm -rf "teatype-venv" || true
}

workspace_directory=$(dirname "$(readlink -f "$0")") # teatype/scripts/deploy
parent_directory=$(dirname "$workspace_directory") # teatype/scripts
grandparent_directory=$(dirname "$parent_directory") # teatype
. "$grandparent_directory/util/bash-helper.sh"

prepare_sudo_env

implemented_trap cleanup

prompt use_django "Do you want to install django support?" "Y/n" "n"
prompt use_fastapi "Do you want to install fastapi support?" "Y/n" "n"
prompt use_gpu "Do you want to install gpu support for ai tools?" "Y/n" "n"

sudo rm -rf "$grandparent_directory/teatype-venv" || true

python3.11 -m venv $grandparent_directory/teatype-venv
. $grandparent_directory/teatype-venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }

python_directory="$grandparent_directory/python"
python3.11 -m pip install --upgrade pip
python3.11 -m pip install -e "$python_directory" --
python3.11 -m pip install -r "$python_directory/requirements/base.txt"
python3.11 -m pip install -r "$python_directory/requirements/build.txt"
python3.11 -m pip install -r "$python_directory/requirements/test.txt"

if [[ $use_django == "Y" || $use_django == "y" ]]; then
    python3.11 -m pip install -r "$python_directory/requirements/django-support.txt"
fi

if [[ $use_fastapi == "Y" || $use_fastapi == "y" ]]; then
    python3.11 -m pip install -r "$python_directory/requirements/fastapi-support.txt"
fi

if [[ $use_gpu == "Y" || $use_gpu == "y" ]]; then
    # python3.11 -m pip install -r "$python_directory/requirements/gpu.txt"
    . "$grandparent_directory/scripts/deploy/4-install-llama-cpp-gpu"
fi