#!/bin/bash

# Copyright (C) 2024-2026 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

workspace_directory=$(dirname "$(readlink -f "$0")") # teatype/scripts/deploy
parent_directory=$(dirname "$workspace_directory") # teatype/scripts
grandparent_directory=$(dirname "$parent_directory") # teatype
. "$grandparent_directory/util/bash-helper.sh"

prepare_sudo_env

cleanup() {
    sudo rm -rf "$grandparent_directory/dist/llama-cpp-python"
}
implemented_trap cleanup

cd "$grandparent_directory"
. teatype-venv/bin/activate

mkdir -p "$grandparent_directory/dist"
cd "$grandparent_directory/dist"

sudo apt-get update -y
sudo apt-get install -y build-essential cmake python3-dev python3-pip git ninja-build libcurl4-openssl-dev gcc-12 g++-12 libgomp1 software-properties-common nvidia-cuda-toolkit
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60 --slave /usr/bin/g++ g++ /usr/bin/g++-12
sudo apt-get autoremove -y

prompt use_gpu "Do you want to install CUDA?" "Y/n" "n"
if [[ $use_gpu == "Y" ]]; then
    sudo add-apt-repository ppa:graphics-drivers/ppa
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-ubuntu2404.pin
    sudo mv cuda-ubuntu2404.pin /etc/apt/preferences.d/cuda-repository-pin-600
    wget https://developer.download.nvidia.com/compute/cuda/13.0.0/local_installers/cuda-repo-ubuntu2404-13-0-local_13.0.0-580.65.06-1_amd64.deb
    sudo dpkg -i cuda-repo-ubuntu2404-13-0-local_13.0.0-580.65.06-1_amd64.deb
    sudo cp /var/cuda-repo-ubuntu2404-13-0-local/cuda-*-keyring.gpg /usr/share/keyrings/
    sudo apt-get update
    sudo apt-get -y install cuda-toolkit-13-0 cuda-drivers
fi
echo 'export PATH=/usr/local/cuda/bin:$PATH' >> ~/.bashrc
echo 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc
. ~/.bashrc

if [ -d "llama-cpp-python" ]; then
    echo "llama-cpp-python directory already exists, skipping cloning"
else
    git clone --recurse-submodules https://github.com/abetlen/llama-cpp-python.git
fi
cd "$grandparent_directory/dist/llama-cpp-python"

# Set environment variables for the build
export PATH=/usr/local/cuda/bin:$PATH
nvcc_path=$(which nvcc)
export CUDACXX="$nvcc_path"
export CMAKE_CUDA_COMPILER="$nvcc_path"
export LLAMA_CMAKE_ARGS="-DGGML_CUDA=on"
export CMAKE_ARGS="-DGGML_CUDA=on -DCUDA_PATH=/usr/local/cuda-13.0 -DCUDAToolkit_ROOT=/usr/local/cuda-13.0 -DCUDAToolkit_INCLUDE_DIR=/usr/local/cuda-13.0/include -DCUDAToolkit_LIBRARY_DIR=/usr/local/cuda-13.0/lib64 -DCMAKE_CUDA_ARCHITECTURES=all-major -DCUDAToolkit_ROOT=/usr/lib/cuda"
export FORCE_CMAKE=1
export CC="/usr/bin/gcc-12"
export CXX="/usr/bin/g++-12"
export CUDAHOSTCXX="/usr/bin/g++-12"

# Run the installation from the cloned directory
python3.13 -m pip install --no-cache-dir .