#!/bin/bash

# Copyright (C) 2024-2026 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

parent_directory=$(dirname "$(readlink -f "$0")")
cd $parent_directory

sudo apt update -y
sudo apt-get remove node nodejs -y

sudo apt-get install nginx -y
sudo systemctl disable nginx

export COREPACK_ENABLE_DOWNLOAD_PROMPT=0

wget -q -O- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

. ~/.bashrc

export NVM_DIR="$HOME/.nvm"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install 20

nvm use 20

nvm alias default 20

corepack enable

export COREPACK_ENABLE_PROMPT=0

corepack prepare pnpm@10.12.1 --activate

corepack install --global pnpm@10.12.1

corepack disable && corepack enable

rm -rf ~/.cache/corepack
corepack prepare yarn@stable --activate

npm uninstall -g corepack
npm install -g corepack
corepack enable

corepack enable

npm i -g corepack@latest && corepack enable