packages:
    - apps/*
    - baseconfig
    - platforms/*
    - components
    - icons
    - hooks
    - style
    - toolkit
    - ../examples/*

ignoredBuiltDependencies:
    - '@parcel/watcher'
    - esbuild
    - node
