packages:
    - api
    - apps
    - apps/*
    - baseconfig
    - buttons
    - components
    - icons
    - hooks
    - style
    - toolkit
    - ../examples/*
    - ../../lockkliye

ignoredBuiltDependencies:
    - '@parcel/watcher'
    - esbuild
    - node
