#!/usr/bin/env python3.11

# Copyright (C) 2024-2026 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Third-party imports
from teatype.cli import BaseCLI
from teatype.logging import *

class Alphabet(BaseCLI):
    """
    A CLI tool to display the alphabet either horizontally or vertically based on user input.
    """
    def meta(self):
        """
        # Metadata for the Alphabet CLI command.

        Returns:
            dict: A dictionary containing command metadata such as name, shorthand, help description, and available flags.
        """
        return {
            'name': 'alphabet',
            'shorthand': 'abc',
            'help': 'Prints the alphabet for big dum dums (listen, but don\'t judge)',
            'flags': [
                {
                    'shorthand': 'v',
                    'name': 'vertical',
                    'help': 'Print the alphabet vertically with indices',
                    'required': False,
                }
            ]
        }

    def execute(self):
        """
        Executes the Alphabet command based on the provided flags.

        If the 'vertical' flag is set, the alphabet is printed vertically with indices.
        Otherwise, the alphabet and corresponding indices are printed horizontally.
        """
        println()  # Add a newline for better readability in the output

        # String containing the alphabet letters separated by ' | '
        alphabet = 'Aa Bb Cc Dd Ee Ff Gg Hh Ii Jj Kk Ll Mm Nn Oo Pp Qq Rr Ss Tt Uu Vv Ww Xx Yy Zz'
        # String containing numerical indices corresponding to each alphabet letter
        alphabet_indices = '1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26'
        # Log the horizontal display of the alphabet
        log(alphabet)
        # Log the corresponding indices for the horizontal display
        log(alphabet_indices)
        
        println()

if __name__ == '__main__':
    Alphabet()