#!/usr/bin/env python3.11

# Copyright (C) 2024-2026 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Standard-library imports
import time

# Third-party imports
from teatype.cli import BaseCLI
from teatype.enum import EscapeColor
from teatype.io import file, path, clear_shell
from teatype.logging import *
from teatype.toolkit import generate_id as proto_generate_id

try:
    import pyperclip
    PYPERCLIP_AVAILABLE = True
except ImportError:
    PYPERCLIP_AVAILABLE = False

class Identifier(BaseCLI):
    def meta(self):
        return {
            'name': 'identifier',
            'shorthand': 'id',
            'help': 'Generates one or multiple (globally) unique identifiers',
            'flags': [
                {
                    'short': 'c',
                    'long': 'count',
                    'help': ['Set the number of identifiers to generate in `burst` mode', '(Default: 100)'],
                    'options': int,
                    'required': False  
                },
                {
                    'short': 'l',
                    'long': 'length',
                    'help': ['Set the length of the identifier/s', '(Default: 60)'],
                    'options': int,
                    'required': False
                },
                {
                    'short': 'm',
                    'long': 'mode',
                    'help': ['Select the mode of the identifier generation', '(Default: single)'],
                    'options': ['burst', 'continous', 'single'],
                    'required': False
                },
                # {
                #     'short': 'o',
                #     'long': 'output',
                #     'help': ['Save the generated identifier/s to the specified file', '(Only works in `single` and `burst` mode)'],
                #     'options': str,
                #     'required': False
                # }
            ]
        }
        
    #########
    # Hooks #
    #########
    
    def execute(self):
        """
        Generate a unique identifier using the teatype library.

            str: A unique identifier string.
        """
        length = self.get_flag('length', default=60)
        # _generate() will always call generate_id with the fixed `length`
        def _generate():
            generated_id = proto_generate_id(truncate=length)
            return generated_id
        
        println()
            
        mode = self.get_flag('mode', default='single')
        number = self.get_flag('count', default=1 if mode != 'burst' else 100)
        if mode == 'continous':
            try:
                history = []
                last_copied = None
                color_cycle = [EscapeColor.MAGENTA, EscapeColor.BLUE]
                color_index = 0
                while True:
                    new_id = _generate()
                    history.append(new_id)

                    if PYPERCLIP_AVAILABLE:
                        pyperclip.copy(new_id)
                        last_copied = new_id

                    clear_shell()
                    
                    println()
                    if PYPERCLIP_AVAILABLE:
                        hint('Pyperclip is enabled. The generated IDs will be copied to your clipboard.')
                        println()
                        
                    hint('Press CTRL+C to stop', use_prefix=False)
                    println()
                    
                    log('Generated IDs:')
                    # Print all but last in gray
                    for item in history[:-1]:
                        marker = ' (copied)' if item == last_copied else ''
                        log(f'    {EscapeColor.GRAY}{item}{marker}{EscapeColor.RESET}')

                    # Print the current ID in color
                    current_color = color_cycle[color_index]
                    color_index = (color_index + 1) % len(color_cycle)

                    marker = f' {EscapeColor.YELLOW}(last copied){EscapeColor.RESET}' if history[-1] == last_copied else ''
                    log(f'    {current_color}{history[-1]}{EscapeColor.RESET}{marker}')

                    time.sleep(0.1)
            except KeyboardInterrupt:
                println()
                println()
                err('Continous mode stopped.', use_prefix=False, verbose=False)
                println()
                return
        else:
            generated_ids = []
            if not isinstance(number, int) or number <= 0:
                err('number must be a positive integer.', raise_exception=True)
                return
            
            for _ in range(number):
                generated_ids.append(_generate())
        
            if len(generated_ids) == 0:
                err('Failed to generate ID, please try again.', raise_exception=False)
                return
            
            if len(generated_ids) > 1:
                log('Generated IDs:')
            else:
                log('Generated ID:')
            printed = 0
            for generated_id in generated_ids:
                log(f'{EscapeColor.MAGENTA}  {generated_id}')
                printed += 1
                if printed == 10:
                    log(f'{EscapeColor.GRAY}  ... and {len(generated_ids) - printed} more.{EscapeColor.RESET}')
                    break
            
            if PYPERCLIP_AVAILABLE:
                println()
                if len(generated_ids) > 1:
                    hint('Results copied to clipboard', use_prefix=False)
                else:
                    hint('Result copied to clipboard', use_prefix=False)
                pyperclip.copy('\n'.join(generated_ids).strip())
                
            println()

if __name__ == '__main__':
    Identifier()