#!/usr/bin/env python3.11

# Copyright (C) 2024-2026 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Third-party imports
from teatype.cli import BaseCLI
from teatype.io import softkill
from teatype.logging import *

class Softkill(BaseCLI):
    def meta(self):
        return {
            'name': 'softkill',
            'shorthand': 'sk',
            'help': 'Soft-kill specified processes by name.',
            'arguments': [
                {
                    'name': 'process-names',
                    'help': 'Names of the processes to be soft-killed, separated by commas.',
                    'required': True
                }
            ],
        }

    def execute(self):
        try:
            process_names = [name.strip() for name in self.get_argument('process-names').split(',')]
            softkill(process_names)
        except Exception:
            err(f"An error occurred while attempting to soft-kill processes", traceback=True)
            
if __name__ == '__main__':
    Softkill()