#!/usr/bin/env python3.11

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# From package imports
from teatype import colorwrap
from teatype.ai.llm import ConversationalAI
from teatype.cli import BaseTUI
from teatype.io import fetch, path, prompt
from teatype.logging import *

DEFAULT_MODEL_PATH = ''
MANUAL_REFRESH = False # If True, the shell will be cleared automatically after each command
DEBUG_MODE = False

class Operations(BaseTUI):
    def meta(self):
        return {
            'name': 'operations',
            'shorthand': 'op',
            'help': 'Teatype Modulo operations interface',
        }
        
    def on_display(self):
        pass
    
    def on_prompt(self):
        pass

    def run(self):
        println()
        
if __name__ == '__main__':
    Operations()