#!/usr/bin/env python3.11

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Package imports
from teatype import colorwrap
from teatype.ai.llm import ConversationalAI
from teatype.cli import BaseTUI
from teatype.io import clear_shell, fetch, path, prompt
from teatype.logging import *
from teatype.modulo.launchpad import LaunchPad
from teatype.modulo.operations import Operations as ModuloOperations

class Operations(BaseTUI):
    def meta(self):
        return {
            'name': 'operations',
            'shorthand': 'op',
            'help': 'Teatype Modulo operations interface',
            'actions': [
                {
                    'name': 'check',
                    'help': 'Check the status of a Modulo unit.',
                    'option_name': 'unit-id',
                    'option': str
                },
                {
                    'name': 'fire',
                    'help': 'Use Launchpad to fire up a Modulo unit.'
                },
                {
                    'name': 'kill',
                    'help': 'Terminate a running Modulo unit.',
                    'option_name': 'unit-id',
                    'option': str  
                },
                {
                    'name': 'list',
                    'help': 'List all available and running Modulo units.'
                }
            ]
        }
        
    def fire(self):
        unit_type = prompt('Which Modulo unit would you like to launch?',
                            options=['backend', 'service', 'workhorse'],
                            return_bool=False)
        unit_name = prompt(f'Enter the name of the {unit_type} unit to launch:',
                           return_bool=False)
        LaunchPad.fire(unit_name, unit_type)
        
    def on_init(self):
        self.operations = ModuloOperations()
        
    def on_prompt(self, user_input:str, option:any=None) -> str:
        match user_input:
            case 'fire':
                self.fire()
            case 'kill':
                self.operations.kill(id=option)
            case 'list':
                pass

if __name__ == '__main__':
    Operations()