#!/bin/bash

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

set -e # Exit immediately if a command exits with a non-zero status

# Set sudo permissions for entire script before further execution and surpress the output
sudo -v >/dev/null 2>&1

parent_path=$(dirname "$(dirname "$(readlink -f "$0")")")
cd "$parent_path"

# Optional: It's good practice to create and activate a Python virtual environment
. ./nightshade-venv/bin/activate

sudo apt-get update -y
sudo apt-get install -y build-essential cmake python3-dev python3-pip git ninja-build libcurl4-openssl-dev gcc-12 g++-12 libgomp1
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60 --slave /usr/bin/g++ g++ /usr/bin/g++-12

git clone --recurse-submodules https://github.com/abetlen/llama-cpp-python.git | echo "Cloned llama-cpp-python repository"
cd llama-cpp-python

# Set environment variables for the build
export PATH=/usr/local/cuda/bin:$PATH
nvcc_path=$(which nvcc)
export CUDACXX="$nvcc_path"
export CMAKE_CUDA_COMPILER="$nvcc_path"
export LLAMA_CMAKE_ARGS="-DGGML_CUDA=on"
export CMAKE_ARGS="-DGGML_CUDA=on -DCUDA_PATH=/usr/local/cuda-13.0 -DCUDAToolkit_ROOT=/usr/local/cuda-13.0 -DCUDAToolkit_INCLUDE_DIR=/usr/local/cuda-12/include -DCUDAToolkit_LIBRARY_DIR=/usr/local/cuda-13.0/lib64 -DCMAKE_CUDA_ARCHITECTURES=all-major -DCUDAToolkit_ROOT=/usr/lib/cuda"
export FORCE_CMAKE=1
export CC="/usr/bin/gcc-12"
export CXX="/usr/bin/g++-12"
export CUDAHOSTCXX="/usr/bin/g++-12"

# Run the installation from the cloned directory
pip install --no-cache-dir .

# Apparently the script of choice