#!/bin/bash

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

set -e

sudo -v >/dev/null 2>&1

sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt-get update -y
sudo apt install -y python3.11 python3.11-dev python3.11-venv python3-pip

workspace_path=$(dirname "$(dirname "$(readlink -f "$0")")")
. "$workspace_path/util/bash-helper.sh"

env_path="$workspace_path/.env"
cp "$workspace_path/.env.template" "$env_path"
if $(uname -r | grep -q "WSL"); then
    echo "Detected WSL instance. Setting flag in .env"
    write_env_variable "$workspace_path/.env" "USING_WSL" "true"
    if [ -n "$WSL_DISTRO_NAME" ]; then
        echo "Detected WSL profile: "$WSL_DISTRO_NAME". Writing to .env"
        write_env_variable "$workspace_path/.env" "WSL_TARGET_PROFILE" "$WSL_DISTRO_NAME"
    fi
else
    echo "Not running inside WSL. Setting flag in .env"
    write_env_variable "$workspace_path/.env" "USING_WSL" "false"
fi

cli_path="$workspace_path/cli"
python_path="$workspace_path/python"
typescript_path="$workspace_path/typescript"

write_env_variable "$env_path" "TEATYPE_CLI_PATH" "$cli_path" 
write_env_variable "$env_path" "TEATYPE_PYTHON_PATH" "$python_path" 
write_env_variable "$env_path" "TEATYPE_TYPESCRIPT_PATH" "$typescript_path" 
write_env_variable "$env_path" "TEATYPE_WORKSPACE_PATH" "$workspace_path"

sudo apt-get install -y libgl1-mesa-glx || true
sudo apt-get install -y libgl1 libglx-mesa0 || true
sudo apt-get install -y chromium-browser vim graphviz openjdk-17-jre-headless jq

. "$env_path"

if [[ ":$PATH:" != *":/usr/local/bin:"* ]]; then
    echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bashrc
    echo "Added /usr/local/bin to PATH in ~/.bashrc"
fi

input_file="$cli_path/proxy.template"
output_file="/usr/local/bin/tt"
sudo rm -f "$output_file"

sed -e "s|{{WORKSPACE_PATH}}|$workspace_path|g" "$input_file" | sudo tee "$output_file" >/dev/null

sudo chmod a+x "$cli_path/tt"
sudo chmod a+x "$input_file"
sudo chmod a+x "$output_file"
echo "Processed script saved to $output_file"


python3.11 -m pip install pip --upgrade
python3.11 -m pip install -e "$python_path"

exec bash