#!/bin/bash

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

set -e # Exit immediately if a command exits with a non-zero status
parent_directory=$(dirname "$(dirname "$(readlink -f "$0")")")
cd "$parent_directory"

python3.11 -m pip install --upgrade pip
python3.11 -m venv teatype-venv
. teatype-venv/bin/activate
python3.11 -m pip install -r $parent_directory/python/requirements/package.txt
python3.11 -m pip install -r $parent_directory/python/requirements/test.txt