#!/bin/bash

# Copyright (C) 2024-2025 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

set -e # Exit immediately if a command exits with a non-zero status

parent_directory=$(dirname "$(dirname "$(readlink -f "$0")")")
python_directory="$parent_directory/python"
cd "$parent_directory"

. "$parent_directory/util/bash-helper.sh"



# sudo rm -rf "teatype-venv" || true

# python3.11 -m venv teatype-venv
# . teatype-venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }

# python3.11 -m pip install --upgrade pip
# python3.11 -m pip install . -e --
# python3.11 -m pip install -r "$python_path/requirements/base.txt"
# python3.11 -m pip install -r "$python_path/requirements/build.txt"
# python3.11 -m pip install -r "$python_path/requirements/test.txt"

# python3.11 -m pip install -r "$python_path/requirements/django-support.txt"
# python3.11 -m pip install -r "$python_path/requirements/fastapi-support.txt"
# python3.11 -m pip install -r "$python_path/requirements/gpu.txt"