#!/usr/bin/env python3.11

# Copyright (C) 2024-2026 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Third-party imports
import redis
from teatype.cli import BaseTUI
from teatype.io import prompt
from teatype.logging import *

class HSDB(BaseTUI):
    def meta(self):
        return {
            'name': 'hsdb',
            'shorthand': 'hsdb',
            'help': 'Hybrid Storage Database (HSDB) management operations',
            'actions': [
                {
                    'name': 'prune',
                    'help': 'Prune the HSDB storaged files and indices',
                }
            ]
        }
        
    def pre_execute(self):
        try:
            redis.Redis().ping()
        except:
            err('Cannot connect to Redis server. Please run the redis server with `tt redis start` before using Modulo operations.',
                exit=True,
                include_symbol=True,
                pad_after=1,
                pad_before=1,
                verbose=False)
            
    def prune(self) -> str:
        confirmation = prompt('Are you sure you want to prune the HSDB storage? This action cannot be undone.')
        if confirmation:
            return 'Prune operation cancelled.'
        
    def on_prompt(self, user_input:str, option:any=None) -> str:
        try:
            match user_input:
                case 'prune':
                    return self.prune()
            return None
        except KeyboardInterrupt:
            return None

if __name__ == '__main__':
    HSDB()